/*
 * Created on 4 May 2016 ( Time 08:38:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tss.hostelmanagement.dao;

import com.tss.hostelmanagement.model.Expense;

/**
 * Expense DAO interface
 * 
 * @author Telosys Tools
 */
public interface ExpenseDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param expenseid
	 * @return the bean found or null if not found 
	 */
	public Expense find( Long expenseid ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param expense
	 * @return true if found, false if not found
	 */
	public boolean load( Expense expense ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param expense
	 * @return the generated value for the auto-incremented column
	 */
	public Long insert(Expense expense) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param expense
	 * @return
	 */
	public int update(Expense expense) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param expenseid
	 * @return
	 */
	public int delete( Long expenseid ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param expense
	 * @return
	 */
	public int delete( Expense expense ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param expenseid
	 * @return
	 */
	public boolean exists( Long expenseid ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param expense
	 * @return
	 */
	public boolean exists( Expense expense ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
