/*
 * Created on 4 May 2016 ( Time 08:38:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tss.hostelmanagement.dao;

import com.tss.hostelmanagement.model.Hostel;

/**
 * Hostel DAO interface
 * 
 * @author Telosys Tools
 */
public interface HostelDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param hostelid
	 * @return the bean found or null if not found 
	 */
	public Hostel find( Long hostelid ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param hostel
	 * @return true if found, false if not found
	 */
	public boolean load( Hostel hostel ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param hostel
	 * @return the generated value for the auto-incremented column
	 */
	public Long insert(Hostel hostel) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param hostel
	 * @return
	 */
	public int update(Hostel hostel) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param hostelid
	 * @return
	 */
	public int delete( Long hostelid ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param hostel
	 * @return
	 */
	public int delete( Hostel hostel ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param hostelid
	 * @return
	 */
	public boolean exists( Long hostelid ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param hostel
	 * @return
	 */
	public boolean exists( Hostel hostel ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
