/*
 * Created on 4 May 2016 ( Time 08:38:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tss.hostelmanagement.dao;

import com.tss.hostelmanagement.model.Payments;

/**
 * Payments DAO interface
 * 
 * @author Telosys Tools
 */
public interface PaymentsDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param paymentid
	 * @return the bean found or null if not found 
	 */
	public Payments find( Long paymentid ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param payments
	 * @return true if found, false if not found
	 */
	public boolean load( Payments payments ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param payments
	 * @return the generated value for the auto-incremented column
	 */
	public Long insert(Payments payments) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param payments
	 * @return
	 */
	public int update(Payments payments) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param paymentid
	 * @return
	 */
	public int delete( Long paymentid ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param payments
	 * @return
	 */
	public int delete( Payments payments ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param paymentid
	 * @return
	 */
	public boolean exists( Long paymentid ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param payments
	 * @return
	 */
	public boolean exists( Payments payments ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
