/*
 * Created on 4 May 2016 ( Time 08:38:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tss.hostelmanagement.dao;

import com.tss.hostelmanagement.model.Registration;

/**
 * Registration DAO interface
 * 
 * @author Telosys Tools
 */
public interface RegistrationDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param registrationid
	 * @return the bean found or null if not found 
	 */
	public Registration find( Long registrationid ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param registration
	 * @return true if found, false if not found
	 */
	public boolean load( Registration registration ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param registration
	 * @return the generated value for the auto-incremented column
	 */
	public Long insert(Registration registration) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param registration
	 * @return
	 */
	public int update(Registration registration) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param registrationid
	 * @return
	 */
	public int delete( Long registrationid ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param registration
	 * @return
	 */
	public int delete( Registration registration ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param registrationid
	 * @return
	 */
	public boolean exists( Long registrationid ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param registration
	 * @return
	 */
	public boolean exists( Registration registration ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
