/*
 * Created on 4 May 2016 ( Time 08:38:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tss.hostelmanagement.model;

import java.io.Serializable;


/**
 * Java bean for 'Expense' entity
 * 
 * @author Telosys Tools
 *
 */
public class Expense implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : expenseId BIGINT 
    private Long expenseId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : amount VARCHAR 
    private String amount;

    // DB : date VARCHAR 
    private String date;

    // DB : deleted INT 
    private Integer deleted;

    // DB : expense VARCHAR 
    private String expense;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setExpenseId( Long expenseId ) {
        this.expenseId = expenseId ;
    }

    public Long getExpenseId() {
        return this.expenseId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setAmount( String amount ) {
        this.amount = amount;
    }
    public String getAmount() {
        return this.amount;
    }

    public void setDate( String date ) {
        this.date = date;
    }
    public String getDate() {
        return this.date;
    }

    public void setDeleted( Integer deleted ) {
        this.deleted = deleted;
    }
    public Integer getDeleted() {
        return this.deleted;
    }

    public void setExpense( String expense ) {
        this.expense = expense;
    }
    public String getExpense() {
        return this.expense;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(expenseId);
        sb.append("|");
        sb.append(amount);
        sb.append("|");
        sb.append(date);
        sb.append("|");
        sb.append(deleted);
        sb.append("|");
        sb.append(expense);
        return sb.toString(); 
    } 


}
