/*
 * Created on 4 May 2016 ( Time 08:38:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tss.hostelmanagement.model;

import java.io.Serializable;


/**
 * Java bean for 'Hostel' entity
 * 
 * @author Telosys Tools
 *
 */
public class Hostel implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : hostelId BIGINT 
    private Long hostelId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : deleted INT 
    private Integer deleted;

    // DB : hostelAddress VARCHAR 
    private String hostelAddress;

    // DB : hostelName VARCHAR 
    private String hostelName;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setHostelId( Long hostelId ) {
        this.hostelId = hostelId ;
    }

    public Long getHostelId() {
        return this.hostelId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDeleted( Integer deleted ) {
        this.deleted = deleted;
    }
    public Integer getDeleted() {
        return this.deleted;
    }

    public void setHostelAddress( String hostelAddress ) {
        this.hostelAddress = hostelAddress;
    }
    public String getHostelAddress() {
        return this.hostelAddress;
    }

    public void setHostelName( String hostelName ) {
        this.hostelName = hostelName;
    }
    public String getHostelName() {
        return this.hostelName;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(hostelId);
        sb.append("|");
        sb.append(deleted);
        sb.append("|");
        sb.append(hostelAddress);
        sb.append("|");
        sb.append(hostelName);
        return sb.toString(); 
    } 


}
