/*
 * Created on 4 May 2016 ( Time 08:38:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tss.hostelmanagement.model;

import java.io.Serializable;


/**
 * Java bean for 'Oppusers' entity
 * 
 * @author Telosys Tools
 *
 */
public class Oppusers implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id BIGINT 
    private Long id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : oppUserName VARCHAR 
    private String oppUserName;

    // DB : oppPassword VARCHAR 
    private String oppPassWord;

    // DB : enabled TINYINT 
    private Byte enabled;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }

    public Long getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setOppUserName( String oppUserName ) {
        this.oppUserName = oppUserName;
    }
    public String getOppUserName() {
        return this.oppUserName;
    }

    public void setOppPassWord( String oppPassWord ) {
        this.oppPassWord = oppPassWord;
    }
    public String getOppPassWord() {
        return this.oppPassWord;
    }

    public void setEnabled( Byte enabled ) {
        this.enabled = enabled;
    }
    public Byte getEnabled() {
        return this.enabled;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(oppUserName);
        sb.append("|");
        sb.append(oppPassWord);
        sb.append("|");
        sb.append(enabled);
        return sb.toString(); 
    } 


}
