/*
 * Created on 4 May 2016 ( Time 08:38:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tss.hostelmanagement.model;

import java.io.Serializable;


/**
 * Java bean for 'Payments' entity
 * 
 * @author Telosys Tools
 *
 */
public class Payments implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : paymentId BIGINT 
    private Long paymentId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : actualAmount VARCHAR 
    private String actualAmount;

    // DB : actualDate VARCHAR 
    private String actualDate;

    // DB : hostlerId BIGINT 
    private Long hostlerId;

    // DB : hostlerName VARCHAR 
    private String hostlerName;

    // DB : paidAmount VARCHAR 
    private String paidAmount;

    // DB : paidDate VARCHAR 
    private String paidDate;

    // DB : deleted INT 
    private Integer deleted;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPaymentId( Long paymentId ) {
        this.paymentId = paymentId ;
    }

    public Long getPaymentId() {
        return this.paymentId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setActualAmount( String actualAmount ) {
        this.actualAmount = actualAmount;
    }
    public String getActualAmount() {
        return this.actualAmount;
    }

    public void setActualDate( String actualDate ) {
        this.actualDate = actualDate;
    }
    public String getActualDate() {
        return this.actualDate;
    }

    public void setHostlerId( Long hostlerId ) {
        this.hostlerId = hostlerId;
    }
    public Long getHostlerId() {
        return this.hostlerId;
    }

    public void setHostlerName( String hostlerName ) {
        this.hostlerName = hostlerName;
    }
    public String getHostlerName() {
        return this.hostlerName;
    }

    public void setPaidAmount( String paidAmount ) {
        this.paidAmount = paidAmount;
    }
    public String getPaidAmount() {
        return this.paidAmount;
    }

    public void setPaidDate( String paidDate ) {
        this.paidDate = paidDate;
    }
    public String getPaidDate() {
        return this.paidDate;
    }

    public void setDeleted( Integer deleted ) {
        this.deleted = deleted;
    }
    public Integer getDeleted() {
        return this.deleted;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(paymentId);
        sb.append("|");
        sb.append(actualAmount);
        sb.append("|");
        sb.append(actualDate);
        sb.append("|");
        sb.append(hostlerId);
        sb.append("|");
        sb.append(hostlerName);
        sb.append("|");
        sb.append(paidAmount);
        sb.append("|");
        sb.append(paidDate);
        sb.append("|");
        sb.append(deleted);
        return sb.toString(); 
    } 


}
