/*
 * Created on 4 May 2016 ( Time 08:38:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tss.hostelmanagement.model;

import java.io.Serializable;


/**
 * Java bean for 'Registration' entity
 * 
 * @author Telosys Tools
 *
 */
public class Registration implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : registrationId BIGINT 
    private Long registrationId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : age VARCHAR 
    private String age;

    // DB : confirmPassword VARCHAR 
    private String confirmPassword;

    // DB : deleted INT 
    private Integer deleted;

    // DB : email VARCHAR 
    private String email;

    // DB : firstName VARCHAR 
    private String firstName;

    // DB : gender VARCHAR 
    private String gender;

    // DB : lastName VARCHAR 
    private String lastName;

    // DB : mobileNumber VARCHAR 
    private String mobileNumber;

    // DB : password VARCHAR 
    private String password;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setRegistrationid( Long registrationId ) {
        this.registrationId = registrationId ;
    }

    public Long getRegistrationId() {
        return this.registrationId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setAge( String age ) {
        this.age = age;
    }
    public String getAge() {
        return this.age;
    }

    public void setConfirmpassword( String confirmPassword ) {
        this.confirmPassword = confirmPassword;
    }
    public String getConfirmPassword() {
        return this.confirmPassword;
    }

    public void setDeleted( Integer deleted ) {
        this.deleted = deleted;
    }
    public Integer getDeleted() {
        return this.deleted;
    }

    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    public void setFirstName( String firstName ) {
        this.firstName = firstName;
    }
    public String getFirstName() {
        return this.firstName;
    }

    public void setGender( String gender ) {
        this.gender = gender;
    }
    public String getGender() {
        return this.gender;
    }

    public void setLastname( String lastName ) {
        this.lastName = lastName;
    }
    public String getLastName() {
        return this.lastName;
    }

    public void setMobileNumber( String mobileNumber ) {
        this.mobileNumber = mobileNumber;
    }
    public String getMobileNumber() {
        return this.mobileNumber;
    }

    public void setPassword( String password ) {
        this.password = password;
    }
    public String getPassword() {
        return this.password;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(registrationId);
        sb.append("|");
        sb.append(age);
        sb.append("|");
        sb.append(confirmPassword);
        sb.append("|");
        sb.append(deleted);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(firstName);
        sb.append("|");
        sb.append(gender);
        sb.append("|");
        sb.append(lastName);
        sb.append("|");
        sb.append(mobileNumber);
        sb.append("|");
        sb.append(password);
        return sb.toString(); 
    } 


}
