/*
 * Created on 4 May 2016 ( Time 08:38:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tss.hostelmanagement.model;

import java.io.Serializable;


/**
 * Java bean for 'Room' entity
 * 
 * @author Telosys Tools
 *
 */
public class Room implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : roomId BIGINT 
    private Long roomId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : deleted INT 
    private Integer deleted;

    // DB : hostelId BIGINT 
    private Long hostelId;

    // DB : noOfBeds VARCHAR 
    private String noOfBeds;

    // DB : roomNumber VARCHAR 
    private String roomNumber;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setRoomId( Long roomId ) {
        this.roomId = roomId ;
    }

    public Long getRoomId() {
        return this.roomId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDeleted( Integer deleted ) {
        this.deleted = deleted;
    }
    public Integer getDeleted() {
        return this.deleted;
    }

    public void setHostelId( Long hostelId ) {
        this.hostelId = hostelId;
    }
    public Long getHostelId() {
        return this.hostelId;
    }

    public void setNoOfBeds( String noOfBeds ) {
        this.noOfBeds = noOfBeds;
    }
    public String getNoOfBeds() {
        return this.noOfBeds;
    }

    public void setRoomNumber( String roomNumber ) {
        this.roomNumber = roomNumber;
    }
    public String getRoomNumber() {
        return this.roomNumber;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(roomId);
        sb.append("|");
        sb.append(deleted);
        sb.append("|");
        sb.append(hostelId);
        sb.append("|");
        sb.append(noOfBeds);
        sb.append("|");
        sb.append(roomNumber);
        return sb.toString(); 
    } 


}
